### ISSUE TITLE
ValueError with new numpy version for MTCNN

### ISSUE THREAD

**Issue by preetham-tn** [timesler/facenet-pytorch#206] opened 2023-03-09 18:34 UTC
When batch of images are passed to mtcnn.detect() , it gives out ValueError for new versions of numpy

When the list is assigned to the numpy array in the following code , for batch of images , list will have inhomogeneous shape after the first dimension which gives out ValueError
https://github.com/timesler/facenet-pytorch/blob/555aa4bec20ca3e7c2ead14e7e39d5bbce203e4b/models/utils/detect_face.py#L183

**Comment by eli-clarity** [comment] 2023-04-02 14:01
I'm Having the same issue, to add a few details: the issue is no face detection in one of the frames in the batch which is than has an empty vector being concatenated to non empty vector (Not sure if it's a numpy version issue, but doesn't fill like numpy should allow it anyway). There is also another issue where you have multiple detections.
Testing with previous versions this issue seems to be persistent down to 2.3.* and you get another issue with the 2.2.* versions.
An ugly workaround I found is to ignore the problematic frame with the following snippet (and force to pick the first frame for each) **Note: this will impact anything you are doing with your data down the line**
`b_i_inds = np.where(image_inds == b_i)[0][0: 1]
if len(b_i_inds) == 0:
    continue`
I guess duplicating another frame is also an option you can consider.

**Comment by timesler** [comment] 2023-04-03 19:40
@preetham-tn @eli-clarity would it be possible for you to provide a reproducible example of this problem?

**Comment by timesler** [comment] 2023-04-06 17:20
This issue should now be fixed with #207 and version 2.5.3 on PyPI. Running `pip install --upgrade facenet-pytorch` should get things up and running properly

**Closed by timesler** 2023-04-06 17:20 UTC

**Comment by preetham-tn** [comment] 2023-04-06 17:21
Thanks @timesler

**Comment by eli-clarity** [comment] 2023-04-13 07:12
Also can confirm the issue is gone, thanks for handling it
